# scanner_engine/output/pdf_report.py

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics import renderPDF

# [핵심] 자동 줄바꿈을 위한 모듈 추가
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle

import sqlite3
import os
import sys
import ipaddress

# 상위 폴더 모듈 참조
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from utils.db_connector import DBConnector

class PDFGenerator:
    def __init__(self):
        self.filename = "Security_Report.pdf"
        self.font_name = 'Helvetica'
        self.bold_font = 'Helvetica-Bold'
        
        # 윈도우 한글 폰트(맑은 고딕) 로드 시도
        try:
            font_path = "C:/Windows/Fonts/malgun.ttf"
            font_bold_path = "C:/Windows/Fonts/malgunbd.ttf"
            
            if os.path.exists(font_path):
                pdfmetrics.registerFont(TTFont('Malgun', font_path))
                self.font_name = 'Malgun'
                if os.path.exists(font_bold_path):
                    pdfmetrics.registerFont(TTFont('Malgun-Bold', font_bold_path))
                    self.bold_font = 'Malgun-Bold'
                else:
                    self.bold_font = 'Malgun'
        except:
            pass # 폰트 로드 실패 시 기본 폰트 사용

    def draw_header(self, c, width, height, title="보안 진단 리포트"):
        """모든 페이지 상단에 고정 헤더 그리기"""
        c.setFillColorRGB(0.1, 0.2, 0.4)
        c.rect(0, height - 70, width, 70, fill=1, stroke=0)
        c.setFillColorRGB(1, 1, 1)
        c.setFont(self.bold_font, 24)
        c.drawString(40, height - 45, title)
        c.setFont(self.font_name, 10)
        c.drawString(width - 200, height - 40, "Generated by Z-Vuln Scan v2.0")

    def draw_pie_chart(self, c, width, height, safe_cnt, vuln_cnt):
        """1페이지 요약 차트 (데이터 0건일 때 예외처리 추가)"""
        
        #데이터가 하나도 없으면 차트를 그리지 않고 텍스트 표시
        if safe_cnt + vuln_cnt == 0:
            c.setFillColor(colors.gray)
            c.setFont(self.font_name, 12)
            c.drawCentredString(width/2, height - 400, "(진단 결과 데이터가 없습니다)")
            return

        d = Drawing(200, 200)
        pc = Pie()
        pc.x = 50
        pc.y = 50
        pc.width = 100
        pc.height = 100
        pc.data = [safe_cnt, vuln_cnt]
        pc.labels = [f"양호 ({safe_cnt})", f"취약 ({vuln_cnt})"]
        
        pc.slices.fontName = self.font_name
        pc.slices.fontSize = 10
        pc.slices.fontColor = colors.black
        
        # 색상: 양호(파랑), 취약(빨강)
        pc.slices[0].fillColor = colors.Color(0.2, 0.6, 1)
        pc.slices[1].fillColor = colors.Color(1, 0.2, 0.2)
        
        pc.sideLabels = 1
        d.add(pc)
        renderPDF.draw(d, c, width/2 - 100, height - 450)

    def sort_key(self, row):
        """IP 주소 기준 정렬"""
        try:
            ip_obj = ipaddress.IPv4Address(row['ip_addr'])
        except:
            ip_obj = ipaddress.IPv4Address('0.0.0.0')
        return (ip_obj, row['code'])

    # [핵심] 텍스트 자동 줄바꿈(Paragraph) 그리기 함수
    def draw_paragraph(self, c, text, x, y, max_width, style):
        """
        긴 텍스트를 받아서 지정된 폭(max_width)에 맞춰 줄바꿈하여 그리고,
        사용된 높이(height)를 반환한다.
        """
        if not text: text = "-"
        
        # DB의 \n 개행 문자를 HTML 태그 <br/>로 변환해야 Paragraph가 인식함
        text = str(text).replace('\n', '<br/>')
        
        p = Paragraph(text, style)
        w, h = p.wrap(max_width, 1000) # 높이는 충분히 계산하도록 설정
        p.drawOn(c, x, y - h) # PDF 좌표계는 아래에서 위로 가므로 y에서 높이만큼 뺌
        
        return h

    def generate(self):
        c = canvas.Canvas(self.filename, pagesize=A4)
        width, height = A4
        
        # 줄바꿈용 스타일 정의
        style_normal = ParagraphStyle(
            name='Normal',
            fontName=self.font_name,
            fontSize=9,
            leading=14, # 줄 간격
            textColor=colors.black
        )

        # DB 연결 및 데이터 조회
        db = DBConnector()
        conn = db.create_connection()
        if not conn: return
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        # OS 타입도 같이 조회하도록 쿼리 수정 가능하나, 현재는 IP/결과 위주
        sql = """
            SELECT A.ip_addr, A.os_type, V.code, V.name, 
                   V.description, V.remediation, 
                   R.status, R.detected_value
            FROM TBL_SCAN_RESULT R
            JOIN TBL_ASSETS A ON R.asset_id = A.asset_id
            JOIN TBL_VULN_DEF V ON R.vuln_id = V.vuln_id
        """
        cursor.execute(sql)
        rows = cursor.fetchall()

        # 데이터 분류
        vuln_list = []
        safe_list = []
        
        for row in rows:
            if row['status'] in ['VULNERABLE', '취약', 'Fail']:
                vuln_list.append(row)
            else:
                safe_list.append(row)

        # 정렬
        vuln_list.sort(key=self.sort_key)
        safe_list.sort(key=self.sort_key)

        total_cnt = len(rows)
        vuln_cnt = len(vuln_list)
        safe_cnt = len(safe_list)
        score = int((safe_cnt / total_cnt) * 100) if total_cnt > 0 else 0
        
        # 대표 IP 추출
        target_summary = "No Assets"
        if rows:
            unique_ips = sorted(list(set(r['ip_addr'] for r in rows)))
            target_summary = unique_ips[0]
            if len(unique_ips) > 1:
                target_summary += f" 외 {len(unique_ips) - 1}대"

        # ==========================================
        # [Page 1] 요약 (Dashboard)
        # ==========================================
        self.draw_header(c, width, height, title="진단 결과 요약 (Executive Summary)")
        y = height - 150
        
        c.setFillColorRGB(0, 0, 0)
        c.setFont(self.bold_font, 14)
        c.drawString(50, y, f"■ 진단 대상: {target_summary}")
        y -= 30
        
        c.setFont(self.bold_font, 14)
        c.drawString(50, y, "■ 보안 등급 (Score)")
        y -= 50
        
        # 점수 박스
        score_color = colors.green if score >= 80 else (colors.orange if score >= 60 else colors.red)
        c.setStrokeColor(score_color)
        c.setLineWidth(2)
        c.rect(50, y, width-100, 40, fill=0)
        
        c.setFillColor(score_color)
        c.setFont(self.bold_font, 20)
        c.drawCentredString(width/2, y+12, f"{score} 점 / 100 점")
        
        # 차트
        self.draw_pie_chart(c, width, height, safe_cnt, vuln_cnt)
        
        y -= 350
        c.setFillColorRGB(0, 0, 0)
        c.setFont(self.font_name, 12)
        summary_text = f"총 {total_cnt}개 항목 중 {vuln_cnt}개의 취약점이 발견되었습니다."
        c.drawCentredString(width/2, y, summary_text)
        
        c.setFont(self.font_name, 10)
        c.setFillColorRGB(0.5, 0.5, 0.5)
        c.drawCentredString(width/2, y-20, "상세 내용은 다음 페이지를 참조하십시오.")
        c.showPage()

        # ==========================================
        # [Page 2~] 취약점 상세 리포트
        # ==========================================
        self.draw_header(c, width, height, title="⚠️ 중요 취약점 상세 내역")
        y = height - 100
        
        if not vuln_list:
            c.setFont(self.bold_font, 12)
            c.drawString(50, y, "발견된 취약점이 없습니다. 보안 상태가 우수합니다.")
        
        current_ip = None

        for row in vuln_list:
            ip = row['ip_addr']
            os_type = row['os_type']
            
            # [공간 체크] 남은 공간이 너무 적으면(약 150px 미만) 다음 페이지로
            if y < 150: 
                c.showPage()
                self.draw_header(c, width, height, title="⚠️ 중요 취약점 상세 내역 (계속)")
                y = height - 100
                if current_ip:
                     c.setFont(self.font_name, 9)
                     c.setFillColorRGB(0.5, 0.5, 0.5)
                     c.drawString(30, y+10, f"(Continue: {current_ip})")
            
            # [IP 헤더] 자산이 바뀔 때마다 표시
            if ip != current_ip:
                c.setFillColorRGB(0.95, 0.95, 0.95)
                c.rect(30, y-5, width-60, 25, fill=1, stroke=0)
                c.setFillColorRGB(0, 0, 0)
                c.setFont(self.bold_font, 12)
                # OS 정보도 함께 출력
                c.drawString(40, y+2, f"Target Asset: {ip} ({os_type})")
                current_ip = ip
                y -= 30

            # [취약점 타이틀]
            c.setFillColorRGB(1, 0.9, 0.9) # 붉은 배경
            c.rect(40, y-5, width-80, 20, fill=1, stroke=0)
            c.setFillColorRGB(0.8, 0, 0)
            c.setFont(self.bold_font, 11)
            c.drawString(50, y, f"[취약] {row['code']} : {row['name']}")
            y -= 25
            
            # [상세 내용 출력 - 자동 줄바꿈 적용]
            left_margin = 100
            content_width = width - 150 # 텍스트 가용 폭
            
            # 1. 현황 (Detected Value)
            c.setFillColorRGB(0, 0, 0)
            c.setFont(self.bold_font, 9)
            c.drawString(60, y-8, "• 현황:")
            
            h_val = self.draw_paragraph(c, row['detected_value'], left_margin, y, content_width, style_normal)
            y -= (h_val + 5) # 사용한 높이만큼 좌표 이동

            # 2. 위험 (Description)
            c.setFont(self.bold_font, 9)
            c.drawString(60, y-8, "• 위험:")
            
            h_desc = self.draw_paragraph(c, row['description'], left_margin, y, content_width, style_normal)
            y -= (h_desc + 5)

            # 3. 조치 (Remediation)
            c.setFillColorRGB(0, 0.2, 0.6) # 파란색
            c.setFont(self.bold_font, 9)
            c.drawString(60, y-8, "• 조치:")
            
            h_rem = self.draw_paragraph(c, row['remediation'], left_margin, y, content_width, style_normal)
            y -= (h_rem + 20) # 항목 간 여유 간격

        c.showPage()

        # ==========================================
        # [Page 3~] 부록: 양호 항목
        # ==========================================
        self.draw_header(c, width, height, title="✅ [부록] 진단 통과 항목 리스트")
        y = height - 100
        
        # 테이블 헤더
        c.setFillColorRGB(0.9, 0.9, 0.9)
        c.rect(40, y, width-80, 20, fill=1, stroke=0)
        c.setFillColorRGB(0, 0, 0)
        c.setFont(self.bold_font, 10)
        c.drawString(50, y+6, "IP 주소")
        c.drawString(150, y+6, "코드")
        c.drawString(220, y+6, "항목명")
        c.drawString(480, y+6, "결과")
        y -= 25
        
        c.setFont(self.font_name, 9)
        
        for row in safe_list:
            if y < 50:
                c.showPage()
                self.draw_header(c, width, height, title="✅ [부록] 진단 통과 항목 리스트")
                y = height - 100
            
            c.drawString(50, y, row['ip_addr'])
            c.drawString(150, y, row['code'])
            # 긴 이름 자르기
            name = row['name']
            if len(name) > 35: name = name[:32] + "..."
            c.drawString(220, y, name)
            
            c.setFillColorRGB(0, 0.5, 0)
            c.drawString(480, y, "Pass")
            c.setFillColorRGB(0, 0, 0)
            
            c.setStrokeColorRGB(0.9, 0.9, 0.9)
            c.line(40, y-5, width-40, y-5)
            y -= 20

        cursor.close()
        conn.close()
        c.save()
        print(f"Report Generated: {os.path.abspath(self.filename)}")

if __name__ == "__main__":
    gen = PDFGenerator()
    gen.generate()