# Copyright (c) 2025 rorena15
# All rights reserved.
# Proprietary License - No redistribution or modification without permission.

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics import renderPDF

# [추가] 자동 줄바꿈(Wrapping)을 위한 모듈 임포트
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle

import sqlite3
import os
import sys
import ipaddress

# 상위 폴더 모듈 참조
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from utils.db_connector import DBConnector

class PDFGenerator:
    def __init__(self):
        self.filename = "Security_Report.pdf"
        self.font_name = 'Helvetica'
        self.bold_font = 'Helvetica-Bold'
        
        try:
            # 윈도우 폰트 경로 (필요시 경로 수정)
            font_path = "C:/Windows/Fonts/malgun.ttf"
            font_bold_path = "C:/Windows/Fonts/malgunbd.ttf"
            
            if os.path.exists(font_path):
                pdfmetrics.registerFont(TTFont('Malgun', font_path))
                self.font_name = 'Malgun'
                if os.path.exists(font_bold_path):
                    pdfmetrics.registerFont(TTFont('Malgun-Bold', font_bold_path))
                    self.bold_font = 'Malgun-Bold'
                else:
                    self.bold_font = 'Malgun'
        except:
            pass

    def draw_header(self, c, width, height, title="보안 진단 리포트"):
        c.setFillColorRGB(0.1, 0.2, 0.4)
        c.rect(0, height - 70, width, 70, fill=1, stroke=0)
        c.setFillColorRGB(1, 1, 1)
        c.setFont(self.bold_font, 24)
        c.drawString(40, height - 45, title)
        c.setFont(self.font_name, 10)
        c.drawString(width - 200, height - 40, "Generated by Z-Vuln Scan v2.0")

    def draw_pie_chart(self, c, width, height, safe_cnt, vuln_cnt):
        """1페이지용 원형 차트 그리기"""
        d = Drawing(200, 200)
        pc = Pie()
        pc.x = 50
        pc.y = 50
        pc.width = 100
        pc.height = 100
        pc.data = [safe_cnt, vuln_cnt]
        pc.labels = [f"양호 ({safe_cnt})", f"취약 ({vuln_cnt})"]
        
        pc.slices.fontName = self.font_name
        pc.slices.fontSize = 10
        pc.slices.fontColor = colors.black
        
        # 색상: 양호(파랑), 취약(빨강)
        pc.slices[0].fillColor = colors.Color(0.2, 0.6, 1)
        pc.slices[1].fillColor = colors.Color(1, 0.2, 0.2)
        
        pc.sideLabels = 1
        pc.simpleLabels = 0
        
        d.add(pc)
        renderPDF.draw(d, c, width/2 - 100, height - 450)

    def sort_key(self, row):
        try:
            ip_obj = ipaddress.IPv4Address(row['ip_addr'])
        except:
            ip_obj = ipaddress.IPv4Address('0.0.0.0')
        return (ip_obj, row['code'])

    # [핵심] Paragraph 그리기 헬퍼 함수
    def draw_paragraph(self, c, text, x, y, max_width, style):
        """
        긴 텍스트를 Paragraph로 변환하여 자동 줄바꿈 처리 후 그리는 함수
        Return: 그려진 텍스트의 높이 (height)
        """
        if not text:
            text = "-"
        # 줄바꿈 문자를 HTML 태그로 변환 (Paragraph용)
        text = str(text).replace('\n', '<br/>')
        
        p = Paragraph(text, style)
        w, h = p.wrap(max_width, 1000) # 높이는 넉넉하게 계산
        p.drawOn(c, x, y - h) # PDF 좌표계는 아래에서 위로 가므로 y에서 높이만큼 뺌
        return h

    def generate(self):
        c = canvas.Canvas(self.filename, pagesize=A4)
        width, height = A4
        
        # 스타일 정의 (자동 줄바꿈용)
        style = ParagraphStyle(
            name='Normal',
            fontName=self.font_name,
            fontSize=9,
            leading=14, # 줄 간격
            textColor=colors.black
        )

        db = DBConnector()
        conn = db.create_connection()
        if not conn: return
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        sql = """
            SELECT A.ip_addr, V.code, V.name, 
                   V.description, V.remediation, 
                   R.status, R.detected_value
            FROM TBL_SCAN_RESULT R
            JOIN TBL_ASSETS A ON R.asset_id = A.asset_id
            JOIN TBL_VULN_DEF V ON R.vuln_id = V.vuln_id
        """
        cursor.execute(sql)
        rows = cursor.fetchall()

        vuln_list = []
        safe_list = []
        
        for row in rows:
            if row['status'] in ['VULNERABLE', '취약', 'Fail']:
                vuln_list.append(row)
            else:
                safe_list.append(row)

        vuln_list.sort(key=self.sort_key)
        safe_list.sort(key=self.sort_key)

        total_cnt = len(rows)
        vuln_cnt = len(vuln_list)
        safe_cnt = len(safe_list)
        score = int((safe_cnt / total_cnt) * 100) if total_cnt > 0 else 0
        
        target_ip = rows[0]['ip_addr'] if rows else "Unknown"
        if len(set(r['ip_addr'] for r in rows)) > 1:
            target_ip += f" 외 {len(set(r['ip_addr'] for r in rows)) - 1}개 자산"

        # ==========================================
        # [Page 1] Executive Summary
        # ==========================================
        self.draw_header(c, width, height, title="진단 결과 요약")
        y = height - 150
        
        c.setFillColorRGB(0, 0, 0)
        c.setFont(self.bold_font, 14)
        c.drawString(50, y, f"■ 진단 대상 그룹: {target_ip}")
        y -= 30
        
        c.setFont(self.bold_font, 14)
        c.drawString(50, y, "■ 보안 안전 등급 (Score)")
        y -= 50
        
        c.setStrokeColorRGB(0.8, 0.8, 0.8)
        c.rect(50, y, width-100, 40, fill=0)
        
        score_color = colors.green if score >= 80 else (colors.orange if score >= 60 else colors.red)
        c.setFillColor(score_color)
        c.setFont(self.bold_font, 20)
        c.drawCentredString(width/2, y+12, f"{score} 점 / 100 점")
        
        self.draw_pie_chart(c, width, height, safe_cnt, vuln_cnt)
        
        y -= 350
        c.setFillColorRGB(0, 0, 0)
        c.setFont(self.font_name, 12)
        summary_text = f"총 {total_cnt}개 진단 항목 중 {vuln_cnt}개의 취약점이 발견되었습니다."
        c.drawCentredString(width/2, y, summary_text)
        
        y -= 20
        c.setFont(self.font_name, 10)
        c.setFillColorRGB(0.5, 0.5, 0.5)
        c.drawCentredString(width/2, y, "상세 내용은 다음 페이지를 참조하십시오.")
        c.showPage()

        # ==========================================
        # [Page 2~] 취약점 상세 리포트 (개선됨)
        # ==========================================
        self.draw_header(c, width, height, title="⚠️ 중요 취약점 상세 내역")
        y = height - 100
        
        if not vuln_list:
            c.setFont(self.bold_font, 12)
            c.drawString(50, y, "발견된 취약점이 없습니다. 보안 상태가 양호합니다.")
        
        current_ip = None

        for row in vuln_list:
            ip = row['ip_addr']
            
            # 1. 공간 부족 여부 미리 체크 (대략 150 높이 필요하다고 가정)
            if y < 150: 
                c.showPage()
                self.draw_header(c, width, height, title="⚠️ 중요 취약점 상세 내역 (계속)")
                y = height - 100
                if current_ip is not None:
                     c.setFont(self.font_name, 9)
                     c.setFillColorRGB(0.5, 0.5, 0.5)
                     c.drawString(30, y+10, f"(Continue: {current_ip})")
            
            # 2. IP 헤더 출력 (IP가 바뀔 때)
            if ip != current_ip:
                # IP 구분선
                c.setFillColorRGB(0.95, 0.95, 0.95)
                c.rect(30, y-5, width-60, 25, fill=1, stroke=0)
                c.setFillColorRGB(0, 0, 0)
                c.setFont(self.bold_font, 12)
                c.drawString(40, y+2, f"Target Asset: {ip}")
                current_ip = ip
                y -= 30

            # 3. 항목 타이틀
            c.setFillColorRGB(1, 0.9, 0.9)
            c.rect(40, y-5, width-80, 20, fill=1, stroke=0)
            c.setFillColorRGB(0.8, 0, 0)
            c.setFont(self.bold_font, 11)
            c.drawString(50, y, f"[취약] {row['code']} : {row['name']}")
            y -= 25
            
            # 4. 상세 내용 출력 (Paragraph 사용으로 자동 줄바꿈)
            left_margin = 100
            content_width = width - 150 # 텍스트가 들어갈 가로 폭
            
            # 현황 (Detected Value)
            c.setFillColorRGB(0, 0, 0)
            c.setFont(self.bold_font, 9)
            c.drawString(60, y-8, "• 현황:")
            
            h_val = self.draw_paragraph(c, row['detected_value'], left_margin, y, content_width, style)
            y -= (h_val + 5) # 그려진 높이만큼 y 이동

            # 위험 (Description)
            c.setFont(self.bold_font, 9)
            c.drawString(60, y-8, "• 위험:")
            
            h_desc = self.draw_paragraph(c, row['description'], left_margin, y, content_width, style)
            y -= (h_desc + 5)

            # 조치 (Remediation)
            c.setFillColorRGB(0, 0.2, 0.6)
            c.setFont(self.bold_font, 9)
            c.drawString(60, y-8, "• 조치:")
            
            h_rem = self.draw_paragraph(c, row['remediation'], left_margin, y, content_width, style)
            y -= (h_rem + 20) # 항목 간 간격 추가

        c.showPage()

        # ==========================================
        # [Page 3~] 부록
        # ==========================================
        self.draw_header(c, width, height, title="✅ [부록] 진단 통과 항목 리스트")
        y = height - 100
        
        c.setFillColorRGB(0.9, 0.9, 0.9)
        c.rect(40, y, width-80, 20, fill=1, stroke=0)
        c.setFillColorRGB(0, 0, 0)
        c.setFont(self.bold_font, 10)
        c.drawString(50, y+6, "IP 주소")
        c.drawString(150, y+6, "코드")
        c.drawString(220, y+6, "항목명")
        c.drawString(480, y+6, "결과")
        y -= 25
        
        c.setFont(self.font_name, 9)
        
        for row in safe_list:
            if y < 50:
                c.showPage()
                self.draw_header(c, width, height, title="✅ [부록] 진단 통과 항목 리스트")
                y = height - 100
            
            c.drawString(50, y, row['ip_addr'])
            c.drawString(150, y, row['code'])
            c.drawString(220, y, row['name'])
            c.setFillColorRGB(0, 0.5, 0)
            c.drawString(480, y, "Pass")
            c.setFillColorRGB(0, 0, 0)
            
            c.setStrokeColorRGB(0.95, 0.95, 0.95)
            c.line(40, y-5, width-40, y-5)
            y -= 20

        cursor.close()
        conn.close()
        c.save()
        print(f"Report Generated: {os.path.abspath(self.filename)}")

if __name__ == "__main__":
    gen = PDFGenerator()
    gen.generate()