# Copyright (c) 2025 rorena15
# All rights reserved.
# Proprietary License - No redistribution or modification without permission.
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
import sqlite3
import os
import sys

# 상위 폴더 모듈 참조
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from utils.db_connector import DBConnector

class PDFGenerator:
    def __init__(self):
        self.filename = "Security_Report.pdf"
        self.font_name = 'Helvetica' # 기본값
        
        # [폰트 설정] 윈도우 맑은 고딕
        try:
            font_path = "C:/Windows/Fonts/malgun.ttf"
            if os.path.exists(font_path):
                pdfmetrics.registerFont(TTFont('Malgun', font_path))
                pdfmetrics.registerFont(TTFont('Malgun-Bold', "C:/Windows/Fonts/malgunbd.ttf")) # 굵은 폰트
                self.font_name = 'Malgun'
                self.bold_font = 'Malgun-Bold'
            else:
                self.bold_font = 'Helvetica-Bold'
        except:
            self.bold_font = 'Helvetica-Bold'

    def draw_header(self, c, width, height):
        """페이지 상단 헤더 그리기"""
        c.setFillColorRGB(0.2, 0.2, 0.6) # 진한 파랑
        c.rect(0, height - 60, width, 60, fill=1, stroke=0) # 상단 배경바
        
        c.setFillColorRGB(1, 1, 1) # 흰색 글씨
        c.setFont(self.bold_font, 20)
        c.drawString(30, height - 40, "Z-Vuln Scan 보안 진단 보고서")
        
        c.setFont(self.font_name, 10)
        c.drawString(width - 250, height - 35, "Generated by Z-Vuln Scan (v1.0 MVP)")
        
        c.setFillColorRGB(0, 0, 0) # 다시 검정으로 복귀

    def generate(self):
        c = canvas.Canvas(self.filename, pagesize=A4)
        width, height = A4
        
        db = DBConnector()
        conn = db.create_connection()
        if not conn: return

        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        # [수정] description, remediation 컬럼 추가 조회
        sql = """
            SELECT A.ip_addr, A.hostname, V.code, V.name, 
                V.description, V.remediation, 
                R.status, R.detected_value
            FROM TBL_SCAN_RESULT R
            JOIN TBL_ASSETS A ON R.asset_id = A.asset_id
            JOIN TBL_VULN_DEF V ON R.vuln_id = V.vuln_id
            ORDER BY A.ip_addr, V.code
        """
        cursor.execute(sql)
        rows = cursor.fetchall()
        
        self.draw_header(c, width, height)
        y = height - 100
        current_ip = None
        
        for row in rows:
            ip = row['ip_addr']
            status = row['status']
            
            # --- IP 그룹 헤더 (이전과 동일) ---
            if ip != current_ip:
                if y < 150: 
                    c.showPage()
                    self.draw_header(c, width, height)
                    y = height - 100
                if current_ip is not None:
                    y -= 20
                    c.setStrokeColorRGB(0.8, 0.8, 0.8)
                    c.line(30, y, width - 30, y)
                    y -= 30

                c.setFillColorRGB(0.95, 0.95, 0.95)
                c.rect(30, y-5, width-60, 25, fill=1, stroke=0)
                c.setFillColorRGB(0, 0, 0)
                c.setFont(self.bold_font, 12)
                hostname = row['hostname'] if row['hostname'] else "Unknown"
                c.drawString(40, y+2, f"■ 대상 자산: {ip}  ({hostname})")
                current_ip = ip
                y -= 30

            # --- 진단 항목 출력 ---
            is_vuln = status in ['VULNERABLE', '취약', 'Fail']
            
            if y < 120: # 상세 내용이 길기 때문에 여유 공간을 더 확보해야 함
                c.showPage()
                self.draw_header(c, width, height)
                y = height - 100
                c.setFont(self.font_name, 9)
                c.setFillColorRGB(0.5, 0.5, 0.5)
                c.drawString(30, y, f"(Continue: {current_ip})")
                y -= 20

            if is_vuln:
                c.setFillColorRGB(0.8, 0, 0) # Red
                status_text = "[취약]"
                c.setFont(self.bold_font, 10)
            else:
                c.setFillColorRGB(0, 0.4, 0.8) # Blue
                status_text = "[양호]"
                c.setFont(self.font_name, 10)

            line = f"{status_text}  {row['code']} : {row['name']}"
            c.drawString(50, y, line)
            
            # --- [핵심 추가] 취약 시 상세 가이드 출력 ---
            if is_vuln:
                y -= 15
                
                # 1. 현황 (detected_value)
                c.setFont(self.bold_font, 9)
                c.setFillColorRGB(0, 0, 0)
                c.drawString(70, y, "• 진단 결과:")
                
                c.setFont(self.font_name, 9)
                c.setFillColorRGB(0.3, 0.3, 0.3)
                det_val = row['detected_value'] if row['detected_value'] else "-"
                c.drawString(130, y, det_val[:70]) # 길이 제한
                y -= 15
                
                # 2. 위험 설명 (Description)
                c.setFont(self.bold_font, 9)
                c.setFillColorRGB(0, 0, 0)
                c.drawString(70, y, "• 위험도:")
                
                c.setFont(self.font_name, 9)
                c.setFillColorRGB(0.3, 0.3, 0.3)
                desc = row['description'] if row['description'] else "설명 없음"
                # 긴 텍스트 줄바꿈 (간단 처리)
                if len(desc) > 70:
                    c.drawString(130, y, desc[:70])
                    y -= 12
                    c.drawString(130, y, desc[70:140])
                else:
                    c.drawString(130, y, desc)
                y -= 15
                
                # 3. 조치 방안 (Remediation) - 파란색 강조
                c.setFont(self.bold_font, 9)
                c.setFillColorRGB(0, 0.2, 0.8) # 진한 파랑
                c.drawString(70, y, "• 조치 방안:")
                
                c.setFont(self.font_name, 9)
                remed = row['remediation'] if row['remediation'] else "가이드 참조"
                
                # 조치 방안은 여러 줄일 수 있음 (\n 기준 분리)
                lines = remed.split('\n')
                for l in lines:
                    c.drawString(130, y, l)
                    y -= 12
                    
                y -= 10 # 항목 간 추가 간격
            else:
                y -= 20

        cursor.close()
        conn.close()
        c.save()
        print(f"Report Generated: {os.path.abspath(self.filename)}")
if __name__ == "__main__":
    gen = PDFGenerator()
    gen.generate()