# Copyright (c) 2025 rorena15
# All rights reserved.
# Proprietary License - No redistribution or modification without permission.
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
import sqlite3
import os
import sys

# 상위 폴더 모듈 참조
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from utils.db_connector import DBConnector

class PDFGenerator:
    def __init__(self):
        self.filename = "Security_Report.pdf"
        self.font_name = 'Helvetica' # 기본값
        
        # [폰트 설정] 윈도우 맑은 고딕
        try:
            font_path = "C:/Windows/Fonts/malgun.ttf"
            if os.path.exists(font_path):
                pdfmetrics.registerFont(TTFont('Malgun', font_path))
                pdfmetrics.registerFont(TTFont('Malgun-Bold', "C:/Windows/Fonts/malgunbd.ttf")) # 굵은 폰트
                self.font_name = 'Malgun'
                self.bold_font = 'Malgun-Bold'
            else:
                self.bold_font = 'Helvetica-Bold'
        except:
            self.bold_font = 'Helvetica-Bold'

    def draw_header(self, c, width, height):
        """페이지 상단 헤더 그리기"""
        c.setFillColorRGB(0.2, 0.2, 0.6) # 진한 파랑
        c.rect(0, height - 60, width, 60, fill=1, stroke=0) # 상단 배경바
        
        c.setFillColorRGB(1, 1, 1) # 흰색 글씨
        c.setFont(self.bold_font, 20)
        c.drawString(30, height - 40, "Z-Vuln Scan 보안 진단 보고서")
        
        c.setFont(self.font_name, 10)
        c.drawString(width - 250, height - 35, "Generated by Z-Vuln Scan (v1.0 MVP)")
        
        c.setFillColorRGB(0, 0, 0) # 다시 검정으로 복귀

    def generate(self):
        c = canvas.Canvas(self.filename, pagesize=A4)
        width, height = A4
        
        # 1. DB 데이터 조회
        db = DBConnector()
        conn = db.create_connection()

        if not conn:
            print("[Error] DB Connection Failed")
            return

        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        # 자산별, 코드별 정렬 조회
        sql = """
            SELECT A.ip_addr, A.hostname, V.code, V.name, R.status, R.detected_value, R.scan_date
            FROM TBL_SCAN_RESULT R
            JOIN TBL_ASSETS A ON R.asset_id = A.asset_id
            JOIN TBL_VULN_DEF V ON R.vuln_id = V.vuln_id
            ORDER BY A.ip_addr, V.code
        """
        cursor.execute(sql)
        rows = cursor.fetchall()
        
        # 초기 페이지 설정
        self.draw_header(c, width, height)
        y = height - 100
        current_ip = None
        
        # 반복문 시작
        for row in rows:
            ip = row['ip_addr']
            status = row['status']
            
            # --- [섹션 1] IP가 바뀔 때마다 자산 헤더 출력 (그룹화) ---
            if ip != current_ip:
                # 페이지 공간 체크 (자산 헤더 + 내용 들어갈 공간 없으면 넘김)
                if y < 150: 
                    c.showPage()
                    self.draw_header(c, width, height)
                    y = height - 100
                
                # 이전 IP와의 간격 띄우기 (첫 IP가 아니면)
                if current_ip is not None:
                    y -= 20
                    c.setStrokeColorRGB(0.8, 0.8, 0.8)
                    c.line(30, y, width - 30, y) # 구분선
                    y -= 30

                # 자산 정보 헤더 (박스 + 텍스트)
                c.setFillColorRGB(0.95, 0.95, 0.95) # 회색 배경
                c.rect(30, y-5, width-60, 25, fill=1, stroke=0)
                
                c.setFillColorRGB(0, 0, 0)
                c.setFont(self.bold_font, 12)
                hostname = row['hostname'] if row['hostname'] else "Unknown"
                c.drawString(40, y+2, f"■ 대상 자산: {ip}  ({hostname})")
                
                current_ip = ip
                y -= 30 # 한 칸 아래로

            # --- [섹션 2] 취약점 항목 출력 ---
            # 페이지 공간 체크
            if y < 50:
                c.showPage()
                self.draw_header(c, width, height)
                y = height - 100
                # 페이지 넘겨도 현재 IP 맥락 유지용 헤더 표시
                c.setFont(self.font_name, 9)
                c.setFillColorRGB(0.5, 0.5, 0.5)
                c.drawString(30, y, f"(Continue: {current_ip})")
                y -= 20

            # 스타일 설정 (취약 vs 양호)
            is_vuln = status in ['VULNERABLE', '취약', 'Fail']
            
            if is_vuln:
                # [강조] 빨간색 + 굵은 글씨
                c.setFillColorRGB(0.8, 0, 0) # Red
                status_text = "[취약]"
                c.setFont(self.bold_font, 10)
            else:
                # [일반] 파란색/검은색 + 일반 글씨
                c.setFillColorRGB(0, 0.4, 0.8) # Blue
                status_text = "[양호]"
                c.setFont(self.font_name, 10)

            # 항목 제목 출력
            # 예: [취약] U-01 root 계정 원격 접속 제한
            line = f"{status_text}  {row['code']} : {row['name']}"
            c.drawString(50, y, line)
            
            # --- [섹션 3] 취약일 때만 상세 내용 출력 (가독성 UP) ---
            if is_vuln:
                y -= 15
                c.setFillColorRGB(0.3, 0.3, 0.3) # 진한 회색
                c.setFont(self.font_name, 9)
                
                # 상세 내용이 너무 길면 자르거나 줄바꿈 처리해야 하지만, 여기선 간단히 길이 제한
                detail = row['detected_value'] if row['detected_value'] else "내용 없음"
                
                # 긴 텍스트 줄바꿈 처리 (간단 구현)
                max_len = 80
                while len(detail) > 0:
                    chunk = detail[:max_len]
                    detail = detail[max_len:]
                    c.drawString(70, y, f"└ {chunk}")
                    y -= 12
                    
                    # 상세 내용 출력 중 페이지 넘어감 방지
                    if y < 40:
                        c.showPage()
                        self.draw_header(c, width, height)
                        y = height - 100
            else:
                # 양호일 때는 상세 내용 생략하거나 한 줄 띄우기만 함
                y -= 20 # 다음 항목과의 간격

        # 마무리
        cursor.close()
        conn.close()
        c.save()
        print(f"Report Generated: {os.path.abspath(self.filename)}")

if __name__ == "__main__":
    gen = PDFGenerator()
    gen.generate()